# Generated by Django 2.1.7 on 2019-02-26 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190226_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='year',
            field=models.IntegerField(help_text='Year of the edition', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
