# Generated by Django 2.1.7 on 2019-04-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190402_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Journal'),
        ),
    ]
