# Generated by Django 2.1.7 on 2019-07-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190722_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('datetop', models.CharField(blank=True, db_column='dateTop', max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('thirdname', models.CharField(blank=True, db_column='thirdName', max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('birthday2', models.CharField(blank=True, db_column='birthDay2', max_length=255, null=True)),
                ('deathday2', models.CharField(blank=True, db_column='deathDay2', max_length=255, null=True)),
                ('wikilink', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entries',
                'managed': False,
            },
        ),
    ]
